version: '3.8'
services:
  java-kata-mysql:
    image: mysql:8.0.35

    platform: linux/amd64
    volumes:
      - news_feed_mysql_volume:/data
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234
      MYSQL_DATABASE: news_feed
    command:
      [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--lower_case_table_names=1' ]

volumes:
  # Named Volume 컨테이너 내부 파일 시스템과 마운트 될 볼륨 위치를 알아서 잡아줌
  news_feed_mysql_volume:
